# Generated by Django 5.2.3 on 2025-06-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="instructions",
            field=models.TextField(blank=True, null=True),
        ),
    ]
